//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDB
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Dept { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<DateTime> Date_Of_Birth { get; set; }
        public string Email { get; set; }
    }
}
